baseurl = "https://lord.re/"
languageCode = "fr-fr"
DefaultContentLanguage = "fr"
title = "/home/lord"
theme = "neoDark"
publishDir = "/home/lord/www/public"


[params]
	sidebartitle = "/home/lord"

[Languages]
[Languages.fr]
weight = 1
[Languages.en]
weight = 2
