name = "Neo Dark"
description = "A minimalist dark theme for Hugo"
license = "wtfpl"
licenselink = ""
source_repo = ""
homepage = "https://lord.re"
tags = ["neodark", "dark", "minimal", "blog", "bloatfree"]
features = ["blog"]
min_version = 0.14

[author]
    name = "Lord"
    homepage = "https://lord.re"
